version: "3.8"
services:
  # Service 1: Our Python App
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis  # Wait for DB to start first

  # Service 2: The Database
  redis:
    image: "redis:alpine" # Download official Redis image
